<?php

namespace ContainerWwTzpsi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoItemDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataProvider\PromoItemDataProvider' shared autowired service.
     *
     * @return \App\DataProvider\PromoItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataProvider/PromoItemDataProvider.php';

        return $container->privates['App\\DataProvider\\PromoItemDataProvider'] = new \App\DataProvider\PromoItemDataProvider(($container->privates['App\\Repository\\PromoRepository'] ?? $container->load('getPromoRepositoryService')));
    }
}
