<?php

namespace ContainerNkVMlvF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UtilisateurController' shared autowired service.
     *
     * @return \App\Controller\UtilisateurController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UtilisateurController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/UserService.php';

        $a = ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService'));
        $b = ($container->services['serializer'] ?? $container->getSerializerService());
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->services['App\\Controller\\UtilisateurController'] = $instance = new \App\Controller\UtilisateurController($a, $b, ($container->services['validator'] ?? $container->getValidatorService()), $b, new \App\Service\UserService($a, $b, ($container->privates['App\\Repository\\ProfilRepository'] ?? $container->load('getProfilRepositoryService')), ($container->privates['api_platform.validator'] ?? $container->load('getApiPlatform_ValidatorService')), $c, ($container->services['swiftmailer.mailer.default'] ?? $container->load('getSwiftmailer_Mailer_DefaultService'))), $c);

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\UtilisateurController', $container));

        return $instance;
    }
}
