<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWwTzpsi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWwTzpsi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWwTzpsi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWwTzpsi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWwTzpsi\App_KernelDevDebugContainer([
    'container.build_hash' => 'WwTzpsi',
    'container.build_id' => '8fd55600',
    'container.build_time' => 1607175934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWwTzpsi');
