<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNkVMlvF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNkVMlvF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNkVMlvF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNkVMlvF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNkVMlvF\App_KernelDevDebugContainer([
    'container.build_hash' => 'NkVMlvF',
    'container.build_id' => 'e0299066',
    'container.build_time' => 1606466102,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNkVMlvF');
