<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerATswK4Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerATswK4Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerATswK4Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerATswK4Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerATswK4Q\App_KernelDevDebugContainer([
    'container.build_hash' => 'ATswK4Q',
    'container.build_id' => '7ee81dc3',
    'container.build_time' => 1612926206,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerATswK4Q');
